import { chromium } from 'playwright-core'
const browser = await chromium.launch({executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',headless:true})
const page = await browser.newPage({viewport:{width:1280,height:800}})
const errors=[]
page.on('console',m=>{if(m.type()==='error')errors.push('console '+m.text())})
page.on('pageerror',e=>errors.push('page '+e.message))
page.on('requestfailed',r=>errors.push('failed '+r.url()+' '+r.failure()?.errorText))
page.on('response',r=>{if(r.status()>=400) errors.push('http '+r.status()+' '+r.url())})
await page.goto('http://127.0.0.1:5174/',{waitUntil:'networkidle',timeout:30000})
console.log('title',await page.locator('body').innerText().then(x=>x.slice(0,800)))
console.log('buttons',await page.locator('button').allTextContents())
await page.screenshot({path:'tools/smoke-shots/custom-title.png'})
await page.click('#start-game'); await page.waitForTimeout(500)
console.log('after start', (await page.locator('body').innerText()).slice(0,1500))
await page.screenshot({path:'tools/smoke-shots/custom-command.png'})
console.log('errors',errors)
await browser.close()
