const fs=require('fs'); const edit=(p,f)=>{let s=fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'').replace(/\r\n/g,'\n'); fs.writeFileSync(p,f(s),'utf8')};
edit('index.html', s=>s.replace('          <div class="tower-actions__buttons">', '          <div class="tower-tier4-branches" id="tower-tier4-branches" hidden></div>\n          <div class="tower-actions__buttons">'));
edit('src/ui/BattleHud.ts', s=>{
 s=s.replace("  coins: number\n}", "  coins: number\n  tier4BranchId: string | null\n  tier4Branches: Array<{ id: string; branch: 'A' | 'B'; name: string; role: string; cost: number; notes: readonly string[] }>\n}");
 s=s.replace('  private readonly upgradeBtn: HTMLButtonElement', '  private readonly tier4BranchesEl: HTMLElement\n  private readonly upgradeBtn: HTMLButtonElement');
 s=s.replace("    this.upgradeBtn = document.getElementById('tower-upgrade') as HTMLButtonElement", "    this.tier4BranchesEl = document.getElementById('tower-tier4-branches') as HTMLElement\n    this.upgradeBtn = document.getElementById('tower-upgrade') as HTMLButtonElement");
 s=s.replace('    this.refreshUpgradeButton(payload.coins)', '    this.renderTier4Branches(payload)\n    this.refreshUpgradeButton(payload.coins)');
 s=s.replace("  private refreshUpgradeButton(coins: number) {\n    const cost", `  private renderTier4Branches(payload: TowerInfoPayload) {\n    this.tier4BranchesEl.replaceChildren()\n    const choices = payload.level === 3 ? payload.tier4Branches : []\n    this.tier4BranchesEl.hidden = choices.length === 0\n    this.upgradeBtn.hidden = choices.length > 0\n    for (const choice of choices) {\n      const button = document.createElement('button')\n      button.type = 'button'\n      button.className = 'tower-tier4-branch'\n      const deficit = Math.max(0, Math.ceil(choice.cost - payload.coins))\n      button.dataset.affordable = String(deficit === 0)\n      button.innerHTML = \`<span>路线 \${choice.branch}</span><strong>\${choice.name}</strong><small>\${choice.role}</small><em>\${choice.cost} 币\${deficit ? \` · 还差 \${deficit}\` : ''}</em>\`\n      button.title = choice.notes.join('；')\n      button.addEventListener('click', () => EventBus.emit(GameEvents.UpgradeTower, { towerId: payload.towerId, branchId: choice.id }))\n      this.tier4BranchesEl.append(button)\n    }\n  }\n\n  private refreshUpgradeButton(coins: number) {\n    const cost`);
 s=s.replace("    if (cost == null) {\n      this.upgradeBtn.innerHTML", "    if (this.currentTowerInfo?.level === 3 && this.currentTowerInfo.tier4Branches.length) {\n      this.renderTier4Branches({ ...this.currentTowerInfo, coins })\n      return\n    }\n    this.upgradeBtn.hidden = false\n    if (cost == null) {\n      this.upgradeBtn.innerHTML");
 s=s.replace("    this.currentTowerInfo = null\n    this.actionPanel.hidden", "    this.currentTowerInfo = null\n    this.tier4BranchesEl.replaceChildren()\n    this.tier4BranchesEl.hidden = true\n    this.actionPanel.hidden");
 return s;
});
edit('src/styles/theme.css', s=>s+`\n.tower-tier4-branches { display:grid; gap:7px; margin:8px 0 4px; }\n.tower-tier4-branches[hidden] { display:none; }\n.tower-tier4-branch { padding:8px 9px; border:1px solid rgba(32,244,230,.45); background:linear-gradient(135deg,#0a1a20,#101228); color:var(--text-body); text-align:left; cursor:pointer; font-family:var(--font-mono); }\n.tower-tier4-branch:hover { border-color:var(--neon-yellow); transform:translateX(-2px); }\n.tower-tier4-branch[data-affordable="false"] { border-color:rgba(255,62,165,.42); }\n.tower-tier4-branch span { float:right; color:var(--neon-cyan); font-size:9px; font-weight:900; }\n.tower-tier4-branch strong,.tower-tier4-branch small,.tower-tier4-branch em { display:block; }\n.tower-tier4-branch strong { color:var(--neon-yellow); font-size:12px; }\n.tower-tier4-branch small { margin-top:3px; color:#9fc5c8; font-size:9px; }\n.tower-tier4-branch em { margin-top:4px; color:var(--neon-pink-soft); font-size:9px; font-style:normal; }\n`);
